version: 2.1
orbs:
  node: circleci/node@2.0.3
  aws-cli: circleci/aws-cli@1.0.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: latest
      - run: npm i
      - run: npm run build:prod
      - aws-cli/setup
      - run: chmod +x scripts/deploy.sh
      - run: ./scripts/deploy.sh
      
workflows:
    build-and-deploy:
      jobs:
        - build