version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-cli: circleci/aws-cli@1.0.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build:prod
  deploy:
    executor:
      name: aws-cli/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: chmod +x scripts/deploy.sh
            - run: ./scripts/deploy.sh
workflows:
    build-and-deploy:
      jobs:
        - build
        - deploy