version: 2.1
orbs:
  node: circleci/node@2.0.3
  aws-cli: circleci/aws-cli@1.0.0
  python: circleci/python@0.3.0

jobs:
  build:
    docker: 
      - image: circleci/python:latest-node
    steps:
      - checkout
      - aws-cli/setup
      - run: pip install awsebcli
      - run: chmod +x scripts/deploy.sh
      - run: ./scripts/deploy.sh
      
workflows:
    build-and-deploy:
      jobs:
        - build